# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HeK2U7k_MLU2_ZOmJpERCZg3y7cRls-
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # 1. Load and Clean Data
# @st.cache_data
# def load_data():
#     df = pd.read_csv("/content/archive (5).zip")
#     df.columns = df.columns.str.strip() # Fixes the hidden spaces
#     # Lowercase column names to match your latest code snippet
#     df.columns = [col.lower().replace(' ', '_') for col in df.columns]
#     # If your CSV has 'title', rename it to 'song_title' to match your snippet
#     if 'title' in df.columns:
#         df.rename(columns={'title': 'song_title'}, inplace=True)
#     return df
# 
# songs = load_data()
# 
# # 2. App Interface
# st.title("🎵 Python-Spotify")
# st.markdown("---")
# 
# # Search Section
# user_input = st.text_input("Search for a song or artist:", placeholder="e.g. Brandon Thomas")
# 
# if user_input:
#     # Search Logic
#     results = songs[
#         songs['song_title'].str.contains(user_input, case=False, na=False) |
#         songs['artist'].str.contains(user_input, case=False, na=False)
#     ].head(5)
# 
#     if results.empty:
#         st.warning("❌ No songs found. Try another search.")
#     else:
#         st.subheader("🔍 Search Results")
# 
#         # Create a layout for results
#         for idx, row in results.iterrows():
#             col1, col2 = st.columns([3, 1])
#             with col1:
#                 st.write(f"**{row['song_title']}** by {row['artist']} ({row['genre']})")
#             with col2:
#                 if st.button(f"Play", key=idx):
#                     st.session_state['selected_song'] = row
# 
# # 3. "Now Playing" and Recommendations
# if 'selected_song' in st.session_state:
#     selected = st.session_state['selected_song']
#     st.markdown("---")
#     st.success(f"▶️ **Now Playing:** {selected['song_title']} by {selected['artist']}")
#     st.info(f"⏱️ **Duration:** {selected['duration']} seconds")
# 
#     # Recommendation Logic
#     st.subheader("✨ Because you liked this")
#     recs = songs[
#         (songs['genre'] == selected['genre']) &
#         (songs['song_title'] != selected['song_title'])
#     ].sort_values(by='popularity', ascending=False).head(3)
# 
#     for idx, row in recs.iterrows():
#         st.write(f"👉 {row['song_title']} - {row['artist']} (Popularity: {row['popularity']})")
